const employee=[
    {
        Name:"Sagar",
        Location:"Kaithal"
    },
    {
        Name:"Rahul",
        Location:"Chandigarh"
    },
    {
        Name:"Rahul KL",
        Location:"Banglore"
    },
    {
        Name:"Sant",
        Location:"Haryana"
    },
    {
        Name:"Sumit",
        Location:"Chandigarh"
    },
    {
        Name:"Ritvik",
        Location:"Kaithal"
    },
    {
        Name:"Ansh",
        Location:"Amritsar"
    },
    {
        Name:"Sachin",
        Location:"Jalandhar"
    },
    {
        Name:"Aditya",
        Location:"Ludhiana"
    },
    {
        Name:"Reyansh",
        Location:"Dharamshala"
    },
    {
        Name:"Gagan",
        Location:"Palampur"
    },
    {
        Name:"Vijay",
        Location:"Goa"
    },
    {
        Name:"Vikas",
        Location:"Banglore"
    },
]
export default employee;
